### ISSUE TITLE
Got "Something happened to main" when try to click on person

### ISSUE THREAD

**Issue by Erol314** [php/web-people#15]
On RFC voting results table, when trying to click on any of the users, instead of user profile i see  the error
![image](https://github.com/php/web-people/assets/24621490/ff629f2a-cf8c-40e9-a09f-59c9dd7040f9)

As example:
https://wiki.php.net/rfc/marking_overriden_methods 
![image](https://github.com/php/web-people/assets/24621490/8d03ac31-e557-44b1-863f-a6a71b0d9e04)

-------------------------------------

Note:  i see this in console , maybe related 
![image](https://github.com/php/web-people/assets/24621490/097f4a81-afa7-419b-bf22-6f29a080ba88)

**Comment by Girgias** [comment]
We are aware of this, however fixing this requires messing with the TLS certificates as far as I've been told, or a whole rebuild of the machine running main.php.net so it's still a W.I.P.

**Comment by tiffany-taylor** [comment]
I believe the TLS certificate issue has been resolved at some point earlier this year. At present, I can click on a person's name from an RFC's voting section, and it correctly loads the person's page. 

@Erol314 can you confirm that it's resolved for you?

**Comment by kelunik** [comment]
Can confirm, let's close this.
